version: "3.8"

services:
  db:
    build: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - "3302:3306"

  web:
    build: ./nginx
    ports:
      - 8000:8000
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
    volumes_from:
      - app
    depends_on:
      - app

  app:
    build: ./python
    command: uwsgi --socket :8001 --module app.wsgi --py-autoreload 1 --logto /tmp/tmp.log
    volumes:
      - ./src:/app
    expose:
      - "8001"
    depends_on:
      - db

volumes:
  db-store:
